name: Workflow Cria artefato

on:
  push:

jobs:

  criar_artefato:
    name: criar artefato
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ vars.NOME }}
        path: .
